In [4]:
import numpy as np

In [5]:
matriz = np.array([12,13,14,15,16,167])
print(matriz)
print(type(matriz))

[ 12  13  14  15  16 167]
<class 'numpy.ndarray'>


In [7]:
matrizfloat = np.array([1,2,3], dtype = np.float64)
print(matrizfloat)

[1. 2. 3.]


In [9]:
aleatorio = np.random.random((5))
print(aleatorio)

[0.50610733 0.28048035 0.92256    0.18893213 0.87511619]


In [11]:
aleatorio = np.random.random((5,3))
print(aleatorio)

[[0.63431114 0.39392921 0.40661544]
 [0.67977189 0.69044005 0.80638796]
 [0.91239005 0.06881665 0.37543803]
 [0.49440879 0.46110109 0.84061013]
 [0.62679924 0.79286332 0.86930611]]


In [16]:
numeros = np.array([10,11,12,13,14,11,10,15,19,20])
print(numeros)
numeros = np.unique(numeros)
print(numeros)

[10 11 12 13 14 11 10 15 19 20]
[10 11 12 13 14 15 19 20]
