In [3]:
import numpy as np

In [9]:
matriz = np.array([12,13,14,15,16,167])
print(matriz)
print(type(matriz))

[ 12  13  14  15  16 167]
<class 'numpy.ndarray'>


In [11]:
matrizfloat = np.array([1,2,3],dtype = np.float64)
print (matrizfloat)

[1. 2. 3.]


In [13]:
aleatorio = np.random.random((5))
print (aleatorio)

[0.92933898 0.79133295 0.45161405 0.14012117 0.60475565]


In [15]:
aleatorio = np.random.random((5,3))
print (aleatorio)

[[0.87581278 0.3334556  0.73200184]
 [0.66626472 0.42839479 0.98511836]
 [0.92628255 0.94961815 0.97228439]
 [0.57162889 0.31779434 0.50970158]
 [0.05193363 0.055701   0.04457863]]


In [19]:
numeros = np.array([10, 11, 12, 13, 14, 11, 10, 15, 19, 20])
print(numeros)
numeros = np.unique(numeros)
print(numeros)

[10 11 12 13 14 11 10 15 19 20]
[10 11 12 13 14 15 19 20]
